services:
  mysql:
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    ports:
#      - "3306:3306"
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: root